package io.evenly.core.domain;

public enum NotificationType {
    EXPENSE_CREATED,
    EXPENSE_UPDATED,
    EXPENSE_DELETED,
    PAYMENT_CREATED,
    PAYMENT_UPDATED,
    PAYMENT_DELETED,
    WORKSPACE_UPDATED,
    WORKSPACE_MEMBER_JOINED,
    BUDGET_THRESHOLD_80,
    BUDGET_LIMIT_REACHED
}
